In [1]:
import pandas as pd
import os

os.getcwd()

'c:\\Users\\vicky\\Downloads\\project_04-main\\project_04-main\\depreciated_ipynb'

In [2]:
file = 'sedan_total.csv'
df = pd.read_csv(file)

In [3]:
df.describe()

,vf_ModelID,vf_ModelYear,mileage,askPrice,msrp,vf_BasePrice,askPrice.1,vf_Doors,vf_EngineCylinders,vf_EngineHP
count,613209.000000,613303.000000,6.133060e+05,6.133060e+05,6.133060e+05,106095.000000,6.133060e+05,611544.000000,559084.000000,343570.000000
mean,2654.925768,2013.188638,6.708743e+04,1.425947e+05,1.627633e+05,28890.744528,1.425947e+05,3.999814,4.692840,200.980465
std,2298.391878,4.565176,6.201534e+04,1.667926e+07,1.772015e+07,13208.252277,1.667926e+07,0.086332,1.121713,72.049983
min,1688.000000,1981.000000,1.000000e+03,0.000000e+00,0.000000e+00,13.900000,0.000000e+00,2.000000,3.000000,11.935094
25%,1834.000000,2011.000000,2.844700e+04,5.750000e+03,5.995000e+03,21950.000000,5.750000e+03,4.000000,4.000000,147.000000
50%,2078.000000,2015.000000,5.015700e+04,1.230800e+04,1.299900e+04,23995.000000,1.230800e+04,4.000000,4.000000,175.000000
75%,2475.000000,2016.000000,9.553000e+04,1.730000e+04,1.869000e+04,34120.000000,1.730000e+04,4.000000,6.000000,241.000000
max,26484.000000,2020.000000,9.999999e+06,2.147484e+09,2.147484e+09,311900.000000,2.147484e+09,5.000000,12.000000,797.000000

In [4]:
df.count()

vf_BodyClass            613306
brandName               613306
vf_Make                 613306
modelName               613209
vf_Model                613209
vf_ModelID              613209
vf_ModelYear            613303
mileage                 613306
askPrice                613306
msrp                    613306
vf_BasePrice            106095
askPrice.1              613306
color                   579514
interiorColor           450288
vf_BodyCabType          613201
vf_Doors                611544
vf_EngineCylinders      559084
vf_EngineHP             343570
vf_FuelTypePrimary      585730
vf_FuelTypeSecondary     52547
vf_Series               466597
vf_Series2               43158
vf_SteeringLocation     143792
vf_TransmissionStyle    172815
vf_Trim                 168332
vf_Trim2                   489
vf_Turbo                 75995
vin                     613306
dtype: int64

In [5]:
df.columns.to_list()

['vf_BodyClass',
 'brandName',
 'vf_Make',
 'modelName',
 'vf_Model',
 'vf_ModelID',
 'vf_ModelYear',
 'mileage',
 'askPrice',
 'msrp',
 'vf_BasePrice',
 'askPrice.1',
 'color',
 'interiorColor',
 'vf_BodyCabType',
 'vf_Doors',
 'vf_EngineCylinders',
 'vf_EngineHP',
 'vf_FuelTypePrimary',
 'vf_FuelTypeSecondary',
 'vf_Series',
 'vf_Series2',
 'vf_SteeringLocation',
 'vf_TransmissionStyle',
 'vf_Trim',
 'vf_Trim2',
 'vf_Turbo',
 'vin']

In [6]:
def where_cols_not_equal(col1,col2):
    comparison = df.loc[df[f'{col1}']!= df[f'{col2}']]
    return comparison

In [7]:
dropped_df = df[[
 'vf_BodyClass',
 'vf_Make',
 'vf_Model',
 'vf_ModelID',
 'vf_ModelYear',
 'mileage',
 'askPrice',
 'msrp',
 'color',
 'vf_BodyCabType',
 'vf_Doors',
 'vf_EngineCylinders',
 'vf_EngineHP',
 'vf_FuelTypePrimary',
 'vf_TransmissionStyle',
 'vin',
]]

In [8]:
df.head()

,vf_BodyClass,brandName,vf_Make,modelName,vf_Model,vf_ModelID,vf_ModelYear,mileage,askPrice,msrp,...,vf_FuelTypePrimary,vf_FuelTypeSecondary,vf_Series,vf_Series2,vf_SteeringLocation,vf_TransmissionStyle,vf_Trim,vf_Trim2,vf_Turbo,vin
0,Sedan/Saloon,HONDA,HONDA,Accord,Accord,1861.0,2011.0,66253,0,0,...,Gasoline,NaN,NaN,NaN,NaN,Automatic,LX,NaN,NaN,17db7a4f0262c5312dbc4f00c126e02dcaac8a17f81a6d...
1,Sedan/Saloon,HONDA,HONDA,Civic,Civic,1863.0,2014.0,81493,0,0,...,Gasoline,NaN,Si,NaN,NaN,Manual/Standard,NaN,NaN,NaN,a9a44eb9d5b82470cdf9692f33597cf8b2d33868a0a537...
2,Sedan/Saloon,CHEVROLET,CHEVROLET,Malibu,Malibu,1834.0,2012.0,79232,0,0,...,Gasoline,NaN,1LT,NaN,NaN,NaN,NaN,NaN,NaN,4a402fc8181916a7fdddeb00509bbd14a278d29265b046...
3,Sedan/Saloon,CHEVROLET,CHEVROLET,Malibu,Malibu,1834.0,2017.0,23056,0,0,...,Gasoline,NaN,LT (1LT),NaN,Left Hand Drive (LHD),NaN,NaN,NaN,Yes,88c484edf48234c4e6d824ae18320de19c7bcb00bdecec...
4,Sedan/Saloon,FORD,FORD,Fiesta,Fiesta,3267.0,2015.0,31793,0,0,...,Flexible Fuel Vehicle (FFV),NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,c96cfc665d912be3a39b4dc3126faa11dd2f9e589b849c...

In [9]:
dropped_df

,vf_BodyClass,vf_Make,vf_Model,vf_ModelID,vf_ModelYear,mileage,askPrice,msrp,color,vf_BodyCabType,vf_Doors,vf_EngineCylinders,vf_EngineHP,vf_FuelTypePrimary,vf_TransmissionStyle,vin
0,Sedan/Saloon,HONDA,Accord,1861.0,2011.0,66253,0,0,Dark Amber Metallic,Not Applicable,4.0,4.0,177.0,Gasoline,Automatic,17db7a4f0262c5312dbc4f00c126e02dcaac8a17f81a6d...
1,Sedan/Saloon,HONDA,Civic,1863.0,2014.0,81493,0,0,Black,Not Applicable,4.0,4.0,205.0,Gasoline,Manual/Standard,a9a44eb9d5b82470cdf9692f33597cf8b2d33868a0a537...
2,Sedan/Saloon,CHEVROLET,Malibu,1834.0,2012.0,79232,0,0,Black Granite Metallic,Not Applicable,4.0,4.0,NaN,Gasoline,NaN,4a402fc8181916a7fdddeb00509bbd14a278d29265b046...
3,Sedan/Saloon,CHEVROLET,Malibu,1834.0,2017.0,23056,0,0,Cajun Red Tintcoat,Not Applicable,4.0,4.0,NaN,Gasoline,NaN,88c484edf48234c4e6d824ae18320de19c7bcb00bdecec...
4,Sedan/Saloon,FORD,Fiesta,3267.0,2015.0,31793,0,0,Tuxedo Black,Not Applicable,4.0,4.0,120.0,Flexible Fuel Vehicle (FFV),NaN,c96cfc665d912be3a39b4dc3126faa11dd2f9e589b849c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613301,Sedan/Saloon,SUBARU,Legacy,2232.0,2018.0,76156,16990,19500,Crystal White Pearl,Not Applicable,4.0,4.0,175.0,Gasoline,Continuously Variable Transmission (CVT),d611b1788a83e34d6a0b416d5f43786440551d8991c8fe...
613302,Sedan/Saloon,HONDA,Accord,1861.0,2003.0,182981,0,0,Graphite Pearl,Not Applicable,4.0,4.0,160.0,Gasoline,Automatic,173aceed0b3a6dae8f91062db88acfe7a900111ccd77c4...
613303,Sedan/Saloon,AUDI,A6,3148.0,2016.0,58176,23850,27750,Florett Silver Metallic,Not Applicable,4.0,6.0,333.0,Gasoline,Automatic,d7ece77d36429418110fc4a5404a9e3d6b7e1963ea412a...
613304,Sedan/Saloon,CHEVROLET,Cruze,1832.0,2017.0,30372,12950,14750,Tungsten Metallic,Not Applicable,4.0,4.0,NaN,Gasoline,Automatic,a5cb8cf50ceddc48947c38fa577edee783bcf8d45bf741...
613305,Sedan/Saloon,BMW,330i,2777.0,2017.0,28975,24500,24500,Mineral White Metallic,Not Applicable,4.0,4.0,248.0,Gasoline,NaN,c783cf329a78c5d9d6603bc45883078782743d4d4f9d0b...

In [10]:
dropped_df['msrp'].value_counts()

0        108248
8995       5040
15995      3551
14995      3091
13995      3077
          ...
6741          1
27227         1
42050         1
5204          1
8528          1
Name: msrp, Length: 27357, dtype: int64

In [11]:
no_ask = dropped_df.loc[dropped_df['msrp']==0]

In [12]:
no_ask_list = no_ask.index.to_list()

In [13]:
dropped_df.drop(no_ask_list)

,vf_BodyClass,vf_Make,vf_Model,vf_ModelID,vf_ModelYear,mileage,askPrice,msrp,color,vf_BodyCabType,vf_Doors,vf_EngineCylinders,vf_EngineHP,vf_FuelTypePrimary,vf_TransmissionStyle,vin
18,Sedan/Saloon,FORD,Taurus,1782.0,2015.0,67588,16462,16462,Ingot Silver Metallic,Not Applicable,4.0,6.0,288.0,Gasoline,NaN,85384fd9108f6e9c75d7a538e4ce8a892170f7dbf42264...
31,Sedan/Saloon,AUDI,S8,3678.0,2015.0,32990,59962,59962,Daytona Gray Pearl Effect,Not Applicable,4.0,8.0,435.0,Gasoline,Automatic,5681b6665e1bfab2557618e54c6b9945bb342840c47d2f...
46,Sedan/Saloon,CHRYSLER,300,1878.0,2017.0,9231,23962,23962,Billet Silver Metallic Clearcoat,Not Applicable,4.0,6.0,292.0,Gasoline,NaN,5c45a1254ea832cffc329eebf700acf918682c1b40f9a7...
50,Sedan/Saloon,LINCOLN,MKZ,1790.0,2016.0,19710,22962,22962,White Platinum Metallic Tri-Coat,Not Applicable,4.0,6.0,300.0,Gasoline,NaN,95592374eecca29c4614b5987b760f9b528e6d3e33c2db...
53,Sedan/Saloon,FORD,Fiesta,3267.0,2011.0,92053,5962,5962,Blue,Not Applicable,4.0,4.0,120.0,Gasoline,NaN,5558ab8c6833c13904fa4a1fbd45c8d00d02f6db9e53fe...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613300,Sedan/Saloon,MERCEDES-BENZ,S-Class,2086.0,2015.0,32190,40999,48000,Designo Diamond White,Not Applicable,4.0,8.0,NaN,Gasoline,NaN,a409283c41c1629b663bc87bc15907a4378e50f3e0970f...
613301,Sedan/Saloon,SUBARU,Legacy,2232.0,2018.0,76156,16990,19500,Crystal White Pearl,Not Applicable,4.0,4.0,175.0,Gasoline,Continuously Variable Transmission (CVT),d611b1788a83e34d6a0b416d5f43786440551d8991c8fe...
613303,Sedan/Saloon,AUDI,A6,3148.0,2016.0,58176,23850,27750,Florett Silver Metallic,Not Applicable,4.0,6.0,333.0,Gasoline,Automatic,d7ece77d36429418110fc4a5404a9e3d6b7e1963ea412a...
613304,Sedan/Saloon,CHEVROLET,Cruze,1832.0,2017.0,30372,12950,14750,Tungsten Metallic,Not Applicable,4.0,4.0,NaN,Gasoline,Automatic,a5cb8cf50ceddc48947c38fa577edee783bcf8d45bf741...
613305,Sedan/Saloon,BMW,330i,2777.0,2017.0,28975,24500,24500,Mineral White Metallic,Not Applicable,4.0,4.0,248.0,Gasoline,NaN,c783cf329a78c5d9d6603bc45883078782743d4d4f9d0b...

In [15]:
dropped_df.to_csv('cleaned_sedan_data.csv', index=False)